# Generated by Django 2.1.7 on 2019-02-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20190228_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trade_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оптовая цена'),
        ),
    ]
